// 자동 생성: build_model_scoreboard.py · 모델 대시보드용 집계
// ⚠️ 집계 숫자만 담는다. 개별 종목 Research Prediction 원본은 들어가지 않는다.
const MODEL_SCOREBOARD = {
 "autoPromotionPolicy": "NONE_MANUAL_APPROVAL_REQUIRED",
 "coverage": {
  "current": "GAEO_COVERAGE_V2_600",
  "note": "500종목 시절(~2026-08-14)과 600종목 구간(2026-08-15~)을 섞지 않고 나눠 집계합니다."
 },
 "decisionTrace": {
  "actionDistribution": {
   "BUY": 176,
   "HOLD": 2150,
   "SELL": 674
  },
  "byModelVersion": {
   "base-2026-08-15-parity-hotfix": {
    "actionDistribution": {
     "BUY": 176,
     "HOLD": 2150,
     "SELL": 674
    },
    "dailyRecordCount": 3000,
    "horizons": {
     "5": {
      "accuracy": null,
      "accuracyDenominator": 0,
      "blocked": 0,
      "evaluated": 0,
      "evaluatedDecisionDays": 0,
      "evidenceStatus": "RECORDS_ACCUMULATING",
      "hit": 0,
      "minUniqueDecisionDays": 20,
      "miss": 0,
      "neutral": 0,
      "pending": 3000,
      "reasons": {
       "future_session": 3000
      },
      "withheld": 0
     }
    },
    "rawRecordCount": 16200,
    "uniqueDecisionDays": 5
   }
  },
  "comparison": {
   "evidenceRef": "research_archive/decisions/comparisons/ae3a50da81e5b0d867e54b92.json.gz",
   "policyVersion": "price-comparison-v1",
   "states": {
    "adjustment_required": 0,
    "comparable": 0,
    "review_required": 0,
    "unknown": 3000
   }
  },
  "currentModelVersion": "base-2026-08-15-parity-hotfix",
  "dailyRecordCount": 3000,
  "disclosure": {
   "byCode": {
    "000070": "unavailable",
    "000080": "unavailable",
    "000100": "unavailable",
    "000120": "unavailable",
    "000150": "needs_review",
    "000210": "unavailable",
    "000240": "unavailable",
    "000250": "unavailable",
    "000270": "unavailable",
    "000370": "unavailable",
    "000400": "unavailable",
    "000430": "unavailable",
    "000490": "needs_review",
    "000500": "needs_review",
    "000640": "needs_review",
    "000660": "needs_review",
    "000670": "needs_review",
    "000720": "unavailable",
    "000810": "unavailable",
    "000880": "needs_review",
    "000990": "unavailable",
    "001040": "unavailable",
    "001060": "needs_review",
    "001120": "unavailable",
    "001200": "unavailable",
    "001230": "needs_review",
    "001270": "unavailable",
    "001390": "unavailable",
    "001430": "unavailable",
    "001440": "unavailable",
    "001450": "unavailable",
    "001500": "unavailable",
    "001510": "unavailable",
    "001530": "unavailable",
    "001570": "unavailable",
    "001680": "unavailable",
    "001720": "unavailable",
    "001740": "unavailable",
    "001750": "unavailable",
    "001800": "unavailable",
    "001820": "unavailable",
    "001940": "unavailable",
    "002020": "unavailable",
    "002030": "unavailable",
    "002240": "unavailable",
    "002310": "unavailable",
    "002320": "unavailable",
    "002350": "unavailable",
    "002380": "unavailable",
    "002710": "unavailable",
    "002790": "unavailable",
    "002810": "unavailable",
    "002840": "unavailable",
    "002900": "unavailable",
    "002960": "unavailable",
    "002990": "unavailable",
    "003000": "unavailable",
    "003030": "unavailable",
    "003070": "unavailable",
    "003090": "unavailable",
    "003160": "unavailable",
    "003200": "unavailable",
    "003230": "unavailable",
    "003240": "unavailable",
    "003280": "unavailable",
    "003300": "unavailable",
    "003380": "unavailable",
    "003470": "unavailable",
    "003490": "unavailable",
    "003530": "unavailable",
    "003540": "unavailable",
    "003550": "unavailable",
    "003570": "unavailable",
    "003620": "unavailable",
    "003670": "unavailable",
    "003690": "unavailable",
    "003850": "unavailable",
    "003920": "unavailable",
    "003960": "unavailable",
    "004000": "unavailable",
    "004020": "unavailable",
    "004170": "unavailable",
    "004360": "unavailable",
    "004370": "unavailable",
    "004430": "unavailable",
    "004490": "unavailable",
    "004690": "unavailable",
    "004700": "unavailable",
    "004710": "unavailable",
    "004800": "unavailable",
    "004980": "unavailable",
    "004990": "unavailable",
    "005070": "unavailable",
    "005090": "unavailable",
    "005180": "unavailable",
    "005250": "unavailable",
    "005290": "unavailable",
    "005300": "unavailable",
    "005380": "unavailable",
    "005420": "unavailable",
    "005430": "unavailable",
    "005440": "unavailable",
    "005490": "unavailable",
    "005500": "unavailable",
    "005610": "unavailable",
    "005690": "unavailable",
    "005720": "unavailable",
    "005810": "unavailable",
    "005830": "unavailable",
    "005850": "unavailable",
    "005880": "unavailable",
    "005930": "unavailable",
    "005940": "unavailable",
    "005950": "unavailable",
    "006040": "unavailable",
    "006110": "unavailable",
    "006120": "unavailable",
    "006220": "unavailable",
    "006260": "unavailable",
    "006280": "unavailable",
    "006340": "unavailable",
    "006360": "unavailable",
    "006380": "unavailable",
    "006400": "unavailable",
    "006650": "unavailable",
    "006730": "unavailable",
    "006800": "unavailable",
    "007070": "unavailable",
    "007310": "unavailable",
    "007340": "unavailable",
    "007390": "unavailable",
    "007660": "unavailable",
    "007690": "unavailable",
    "007700": "unavailable",
    "007810": "unavailable",
    "008060": "unavailable",
    "008490": "unavailable",
    "008730": "unavailable",
    "008770": "unavailable",
    "008930": "unavailable",
    "009150": "unavailable",
    "009155": "unavailable",
    "009160": "unavailable",
    "009240": "unavailable",
    "009290": "unavailable",
    "009410": "unavailable",
    "009420": "unavailable",
    "009450": "unavailable",
    "009540": "unavailable",
    "009830": "unavailable",
    "009900": "unavailable",
    "009970": "unavailable",
    "010060": "unavailable",
    "010120": "unavailable",
    "010130": "unavailable",
    "010140": "unavailable",
    "010170": "unavailable",
    "010690": "unavailable",
    "010780": "unavailable",
    "010820": "unavailable",
    "010950": "unavailable",
    "011070": "unavailable",
    "011170": "unavailable",
    "011200": "unavailable",
    "011210": "unavailable",
    "011760": "unavailable",
    "011780": "unavailable",
    "011790": "unavailable",
    "011930": "unavailable",
    "012030": "unavailable",
    "012330": "unavailable",
    "012450": "unavailable",
    "012630": "unavailable",
    "012750": "unavailable",
    "013030": "unavailable",
    "014620": "unavailable",
    "014680": "unavailable",
    "014820": "unavailable",
    "014830": "unavailable",
    "015360": "unavailable",
    "015760": "unavailable",
    "016360": "unavailable",
    "016380": "unavailable",
    "016590": "unavailable",
    "016610": "unavailable",
    "016800": "unavailable",
    "017390": "unavailable",
    "017670": "unavailable",
    "017800": "unavailable",
    "017810": "unavailable",
    "017860": "unavailable",
    "017900": "unavailable",
    "017940": "unavailable",
    "017960": "unavailable",
    "018250": "unavailable",
    "018260": "unavailable",
    "018290": "unavailable",
    "018670": "unavailable",
    "018880": "unavailable",
    "019170": "unavailable",
    "019210": "unavailable",
    "020000": "unavailable",
    "020150": "unavailable",
    "020560": "unavailable",
    "021240": "unavailable",
    "022100": "unavailable",
    "023160": "unavailable",
    "023530": "unavailable",
    "023590": "unavailable",
    "024110": "unavailable",
    "024720": "unavailable",
    "025540": "unavailable",
    "025860": "unavailable",
    "026890": "unavailable",
    "026960": "unavailable",
    "027410": "unavailable",
    "028050": "unavailable",
    "028260": "unavailable",
    "028300": "unavailable",
    "028670": "unavailable",
    "029460": "unavailable",
    "029530": "unavailable",
    "029780": "unavailable",
    "030000": "unavailable",
    "030190": "unavailable",
    "030200": "unavailable",
    "030210": "unavailable",
    "030520": "unavailable",
    "030530": "unavailable",
    "030610": "unavailable",
    "031210": "unavailable",
    "031330": "unavailable",
    "031430": "unavailable",
    "031980": "unavailable",
    "032190": "unavailable",
    "032350": "unavailable",
    "032500": "unavailable",
    "032640": "unavailable",
    "032820": "unavailable",
    "032830": "unavailable",
    "033100": "unavailable",
    "033240": "unavailable",
    "033270": "unavailable",
    "033500": "unavailable",
    "033640": "unavailable",
    "033780": "unavailable",
    "034020": "unavailable",
    "034120": "unavailable",
    "034220": "unavailable",
    "034230": "unavailable",
    "034310": "unavailable",
    "034730": "unavailable",
    "034830": "unavailable",
    "034950": "unavailable",
    "035250": "unavailable",
    "035420": "unavailable",
    "035720": "unavailable",
    "035760": "unavailable",
    "035900": "unavailable",
    "036460": "unavailable",
    "036530": "unavailable",
    "036540": "unavailable",
    "036570": "unavailable",
    "036810": "unavailable",
    "036830": "unavailable",
    "036930": "unavailable",
    "037460": "unavailable",
    "037710": "unavailable",
    "038500": "unavailable",
    "039030": "unavailable",
    "039130": "unavailable",
    "039200": "unavailable",
    "039490": "unavailable",
    "041510": "unavailable",
    "041830": "unavailable",
    "041960": "unavailable",
    "042660": "unavailable",
    "042700": "unavailable",
    "043260": "unavailable",
    "044490": "unavailable",
    "045100": "unavailable",
    "046890": "unavailable",
    "047040": "unavailable",
    "047050": "unavailable",
    "047810": "unavailable",
    "048410": "unavailable",
    "050890": "unavailable",
    "051600": "unavailable",
    "051900": "unavailable",
    "051910": "unavailable",
    "052020": "unavailable",
    "052400": "unavailable",
    "052690": "unavailable",
    "053610": "unavailable",
    "053800": "unavailable",
    "055550": "unavailable",
    "056080": "unavailable",
    "056190": "unavailable",
    "058430": "unavailable",
    "058470": "unavailable",
    "058610": "unavailable",
    "058650": "unavailable",
    "059090": "unavailable",
    "060250": "unavailable",
    "060280": "unavailable",
    "060370": "unavailable",
    "060980": "unavailable",
    "062040": "unavailable",
    "064290": "unavailable",
    "064350": "unavailable",
    "064400": "unavailable",
    "064760": "unavailable",
    "064960": "unavailable",
    "065350": "unavailable",
    "066570": "unavailable",
    "066970": "unavailable",
    "067160": "unavailable",
    "067310": "unavailable",
    "068270": "unavailable",
    "068760": "unavailable",
    "069260": "unavailable",
    "069620": "unavailable",
    "069960": "unavailable",
    "071050": "unavailable",
    "071320": "unavailable",
    "071840": "unavailable",
    "071970": "unavailable",
    "072710": "unavailable",
    "073240": "unavailable",
    "074600": "unavailable",
    "075580": "unavailable",
    "077970": "unavailable",
    "078600": "unavailable",
    "078930": "unavailable",
    "079160": "unavailable",
    "079550": "unavailable",
    "079900": "unavailable",
    "080220": "unavailable",
    "081660": "unavailable",
    "082640": "unavailable",
    "082740": "unavailable",
    "082920": "unavailable",
    "083450": "unavailable",
    "083650": "unavailable",
    "084010": "unavailable",
    "084370": "unavailable",
    "085620": "unavailable",
    "085660": "unavailable",
    "086280": "unavailable",
    "086450": "unavailable",
    "086520": "unavailable",
    "086790": "unavailable",
    "086900": "unavailable",
    "087010": "unavailable",
    "088350": "unavailable",
    "089030": "unavailable",
    "089590": "unavailable",
    "089860": "unavailable",
    "089890": "unavailable",
    "089970": "unavailable",
    "090360": "unavailable",
    "090430": "unavailable",
    "090460": "unavailable",
    "090710": "unavailable",
    "092230": "unavailable",
    "092790": "unavailable",
    "093050": "unavailable",
    "093320": "unavailable",
    "093370": "unavailable",
    "094170": "unavailable",
    "095340": "unavailable",
    "095610": "unavailable",
    "095660": "unavailable",
    "096530": "unavailable",
    "096760": "unavailable",
    "096770": "unavailable",
    "097230": "unavailable",
    "097520": "unavailable",
    "097950": "unavailable",
    "098460": "unavailable",
    "099190": "unavailable",
    "099320": "unavailable",
    "100090": "unavailable",
    "100790": "unavailable",
    "100840": "unavailable",
    "101490": "unavailable",
    "102710": "unavailable",
    "102940": "unavailable",
    "103140": "unavailable",
    "103590": "unavailable",
    "104700": "unavailable",
    "104830": "unavailable",
    "105560": "unavailable",
    "105630": "unavailable",
    "108320": "unavailable",
    "108490": "unavailable",
    "108670": "unavailable",
    "111770": "unavailable",
    "112040": "unavailable",
    "112610": "unavailable",
    "114090": "unavailable",
    "115180": "unavailable",
    "119850": "unavailable",
    "120110": "unavailable",
    "121600": "unavailable",
    "122640": "unavailable",
    "122870": "unavailable",
    "122900": "unavailable",
    "123890": "unavailable",
    "126340": "unavailable",
    "126560": "unavailable",
    "126720": "unavailable",
    "127120": "unavailable",
    "128940": "unavailable",
    "130660": "unavailable",
    "131290": "unavailable",
    "131970": "unavailable",
    "137310": "unavailable",
    "137400": "unavailable",
    "138040": "unavailable",
    "138930": "unavailable",
    "139130": "unavailable",
    "139480": "unavailable",
    "140410": "unavailable",
    "140860": "unavailable",
    "141080": "unavailable",
    "145020": "unavailable",
    "145720": "unavailable",
    "145990": "unavailable",
    "160190": "unavailable",
    "161000": "unavailable",
    "161390": "unavailable",
    "161580": "unavailable",
    "161890": "unavailable",
    "166090": "unavailable",
    "170900": "unavailable",
    "170920": "unavailable",
    "171090": "unavailable",
    "175330": "unavailable",
    "178320": "unavailable",
    "178920": "unavailable",
    "180640": "unavailable",
    "181710": "unavailable",
    "183190": "unavailable",
    "183300": "unavailable",
    "185750": "unavailable",
    "189300": "unavailable",
    "192080": "unavailable",
    "192400": "unavailable",
    "192650": "unavailable",
    "192820": "unavailable",
    "195870": "unavailable",
    "195940": "unavailable",
    "196170": "unavailable",
    "200880": "unavailable",
    "204270": "unavailable",
    "204320": "unavailable",
    "207940": "unavailable",
    "210980": "unavailable",
    "211050": "unavailable",
    "213420": "unavailable",
    "214150": "unavailable",
    "214320": "unavailable",
    "214370": "unavailable",
    "214430": "unavailable",
    "214450": "unavailable",
    "215200": "unavailable",
    "218410": "unavailable",
    "222080": "unavailable",
    "222800": "unavailable",
    "225570": "unavailable",
    "226950": "unavailable",
    "229640": "unavailable",
    "232140": "unavailable",
    "237690": "unavailable",
    "240810": "unavailable",
    "241560": "unavailable",
    "241710": "unavailable",
    "247540": "unavailable",
    "248070": "unavailable",
    "249420": "unavailable",
    "251270": "unavailable",
    "251970": "unavailable",
    "252990": "unavailable",
    "253450": "unavailable",
    "257720": "unavailable",
    "259960": "unavailable",
    "263750": "unavailable",
    "267250": "unavailable",
    "267260": "unavailable",
    "267270": "unavailable",
    "268280": "unavailable",
    "271560": "unavailable",
    "271940": "unavailable",
    "272210": "unavailable",
    "272290": "unavailable",
    "272450": "unavailable",
    "277810": "unavailable",
    "278280": "unavailable",
    "278470": "unavailable",
    "279570": "unavailable",
    "280360": "unavailable",
    "281740": "unavailable",
    "281820": "unavailable",
    "282330": "unavailable",
    "284740": "unavailable",
    "285130": "unavailable",
    "286940": "unavailable",
    "290650": "unavailable",
    "293490": "unavailable",
    "294870": "unavailable",
    "295310": "unavailable",
    "298000": "unavailable",
    "298020": "unavailable",
    "298040": "unavailable",
    "298050": "unavailable",
    "298380": "unavailable",
    "298690": "unavailable",
    "300720": "unavailable",
    "302440": "unavailable",
    "306200": "unavailable",
    "307950": "unavailable",
    "310210": "unavailable",
    "316140": "unavailable",
    "317400": "unavailable",
    "317450": "unavailable",
    "319400": "unavailable",
    "319660": "unavailable",
    "322000": "unavailable",
    "323280": "unavailable",
    "323410": "unavailable",
    "326030": "unavailable",
    "328130": "unavailable",
    "329180": "unavailable",
    "336260": "unavailable",
    "336370": "unavailable",
    "336570": "unavailable",
    "340570": "unavailable",
    "344820": "unavailable",
    "347700": "unavailable",
    "347850": "unavailable",
    "348210": "unavailable",
    "348340": "unavailable",
    "348370": "unavailable",
    "352820": "unavailable",
    "353200": "unavailable",
    "356860": "unavailable",
    "357780": "unavailable",
    "358570": "unavailable",
    "361610": "unavailable",
    "365340": "unavailable",
    "373220": "unavailable",
    "375500": "unavailable",
    "376300": "unavailable",
    "376900": "unavailable",
    "377300": "unavailable",
    "377740": "unavailable",
    "381620": "unavailable",
    "381970": "unavailable",
    "383220": "unavailable",
    "383310": "unavailable",
    "383800": "unavailable",
    "388210": "unavailable",
    "388720": "unavailable",
    "397030": "unavailable",
    "399720": "unavailable",
    "402340": "unavailable",
    "403550": "unavailable",
    "403870": "unavailable",
    "417200": "unavailable",
    "420770": "unavailable",
    "437730": "unavailable",
    "439260": "unavailable",
    "440110": "unavailable",
    "443060": "unavailable",
    "445680": "unavailable",
    "450080": "unavailable",
    "452260": "unavailable",
    "453340": "unavailable",
    "454910": "unavailable",
    "456040": "unavailable",
    "456160": "unavailable",
    "457190": "unavailable",
    "458870": "unavailable",
    "460860": "unavailable",
    "460930": "unavailable",
    "462870": "unavailable",
    "466100": "unavailable",
    "475150": "unavailable",
    "475560": "unavailable",
    "475830": "unavailable",
    "476060": "unavailable",
    "477850": "unavailable",
    "483650": "unavailable",
    "484870": "unavailable",
    "489790": "unavailable",
    "490470": "unavailable",
    "491000": "unavailable",
    "499790": "unavailable",
    "950160": "unavailable"
   },
   "observedAt": "2026-09-17T00:34:36+00:00",
   "scope": "기업행사 및 거래소 시장조치. 뉴스 전체 확인이 아닙니다.",
   "statuses": {
    "checked_no_event": 0,
    "event_found": 0,
    "needs_review": 9,
    "unavailable": 591
   }
  },
  "examples": [
   {
    "base": 60200,
    "baseAt": "2026-09-11 종가 (16:04 수집) · ⚠️ 1종목 지연",
    "call": "HOLD",
    "code": "000070",
    "comparisonPath": "research_archive/decisions/comparisons/ae3a50da81e5b0d867e54b92.json.gz",
    "comparisonReason": "corporate_action_unverified",
    "comparisonState": "unknown",
    "decisionAt": "2026-09-11 16:14",
    "outcomePath": "research_archive/decisions/outcomes/2026-09.json",
    "reason": "future_session",
    "recordId": "c2f6862f8bb9f97d233e2e0d80efe03a",
    "sourcePath": "research_archive/decisions/originals/2026/09/11/f2d05a79eb66788d9c869851.jsonl.gz",
    "status": "pending"
   },
   {
    "base": 60600,
    "baseAt": "2026-09-14 13:06 장중 · ⚠️ 1종목 지연",
    "call": "HOLD",
    "code": "000070",
    "comparisonPath": "research_archive/decisions/comparisons/ae3a50da81e5b0d867e54b92.json.gz",
    "comparisonReason": "corporate_action_unverified",
    "comparisonState": "unknown",
    "decisionAt": "2026-09-14 13:13",
    "outcomePath": "research_archive/decisions/outcomes/2026-09.json",
    "reason": "future_session",
    "recordId": "49086ae645fcd35b1d8389b44c840dda",
    "sourcePath": "research_archive/decisions/originals/2026/09/14/e1bb71a2b16d3d9d00154752.jsonl.gz",
    "status": "pending"
   },
   {
    "base": 59800,
    "baseAt": "2026-09-15 종가 (16:00 수집) · ⚠️ 1종목 지연",
    "call": "HOLD",
    "code": "000070",
    "comparisonPath": "research_archive/decisions/comparisons/ae3a50da81e5b0d867e54b92.json.gz",
    "comparisonReason": "corporate_action_unverified",
    "comparisonState": "unknown",
    "decisionAt": "2026-09-15 16:33",
    "outcomePath": "research_archive/decisions/outcomes/2026-09.json",
    "reason": "future_session",
    "recordId": "c9be48ff7a6cddcda8a608211106ed7d",
    "sourcePath": "research_archive/decisions/originals/2026/09/15/d6539a75930f00bf074a935e.jsonl.gz",
    "status": "pending"
   }
  ],
  "execution": {
   "analysisCount": 3000,
   "decisionOriginalHash": "75c58a851fd403aee3f7f0310669201b3728a98c6b795fd65f97d05f428701ac",
   "decisionOriginalId": "adcabb0d90905471d1500d7d",
   "event": "workflow_dispatch",
   "headSha": "5a3620aa369b5bc17803bf0035dcd2d414070f8c",
   "runAttempt": "1",
   "runId": "35161807080"
  },
  "horizons": {
   "5": {
    "accuracy": null,
    "accuracyDenominator": 0,
    "blocked": 0,
    "evaluated": 0,
    "evaluatedDecisionDays": 0,
    "evidenceStatus": "RECORDS_ACCUMULATING",
    "hit": 0,
    "minUniqueDecisionDays": 20,
    "miss": 0,
    "neutral": 0,
    "pending": 3000,
    "reasons": {
     "future_session": 3000
    },
    "withheld": 0
   }
  },
  "lastVerifiedAt": "2026-09-17T00:34:36+00:00",
  "latestDecisionAt": "2026-09-17 09:33",
  "limitations": [
   "원본 보존을 시작한 실제 자동분석만 연결합니다. 과거 판단을 재구성하지 않습니다.",
   "하루 여러 판단을 보존하지만 성적은 종목·판단일당 마지막 자동판단 1건입니다.",
   "현재 시세 자료에는 수정주가·기업행사 조정 확인 근거가 없어 평가일이 와도 확인 전에는 채점을 보류합니다.",
   "기존 일별 이력 성적은 별도 참고 집계입니다. 아래 엄격한 원본 연결 건수와 같은 분모가 아닙니다.",
   "기본모델은 기존 5거래일 기준입니다. 연구모델의 5·20·60거래일 검증은 그대로 유지합니다."
  ],
  "quality": {
   "activeCohort": "base-2026-08-15-parity-hotfix|unrecorded|grading_v1_2026-08-16|GAEO_COVERAGE_V2_600",
   "cohorts": {
    "base-2026-08-15-parity-hotfix|unrecorded|grading_v1_2026-08-16|GAEO_COVERAGE_V2_600": {
     "actions": {
      "BUY": {
       "accuracy95": null,
       "accuracyDenominator": 0,
       "accuracyPct": null,
       "blocked": 0,
       "evaluated": 0,
       "evaluatedDecisionDays": 0,
       "evidenceStatus": "INSUFFICIENT_EVIDENCE",
       "gradedDecisionDays": 0,
       "hit": 0,
       "minUniqueDecisionDays": 20,
       "miss": 0,
       "neutral": 0,
       "pending": 176,
       "recordCount": 176,
       "uniqueDecisionDays": 5,
       "withheld": 0
      },
      "HOLD": {
       "accuracy95": null,
       "accuracyDenominator": 0,
       "accuracyPct": null,
       "blocked": 0,
       "evaluated": 0,
       "evaluatedDecisionDays": 0,
       "evidenceStatus": "INSUFFICIENT_EVIDENCE",
       "gradedDecisionDays": 0,
       "hit": 0,
       "minUniqueDecisionDays": 20,
       "miss": 0,
       "neutral": 0,
       "pending": 2150,
       "recordCount": 2150,
       "uniqueDecisionDays": 5,
       "withheld": 0
      },
      "SELL": {
       "accuracy95": null,
       "accuracyDenominator": 0,
       "accuracyPct": null,
       "blocked": 0,
       "evaluated": 0,
       "evaluatedDecisionDays": 0,
       "evidenceStatus": "INSUFFICIENT_EVIDENCE",
       "gradedDecisionDays": 0,
       "hit": 0,
       "minUniqueDecisionDays": 20,
       "miss": 0,
       "neutral": 0,
       "pending": 674,
       "recordCount": 674,
       "uniqueDecisionDays": 5,
       "withheld": 0
      }
     },
     "bins": {
      "confidence": {
       "BUY": [
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "0~39",
         "lower": 0,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 41,
         "recordCount": 41,
         "uniqueDecisionDays": 5,
         "upperExclusive": 40,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "40~49",
         "lower": 40,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 106,
         "recordCount": 106,
         "uniqueDecisionDays": 5,
         "upperExclusive": 50,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "50~59",
         "lower": 50,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 28,
         "recordCount": 28,
         "uniqueDecisionDays": 5,
         "upperExclusive": 60,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "60~69",
         "lower": 60,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 70,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "70~79",
         "lower": 70,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 1,
         "recordCount": 1,
         "uniqueDecisionDays": 1,
         "upperExclusive": 80,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "80~89",
         "lower": 80,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 90,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "90~100",
         "lower": 90,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 101,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "기록 없음",
         "lower": null,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": null,
         "withheld": 0
        }
       ],
       "SELL": [
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "0~39",
         "lower": 0,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 189,
         "recordCount": 189,
         "uniqueDecisionDays": 5,
         "upperExclusive": 40,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "40~49",
         "lower": 40,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 163,
         "recordCount": 163,
         "uniqueDecisionDays": 5,
         "upperExclusive": 50,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "50~59",
         "lower": 50,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 160,
         "recordCount": 160,
         "uniqueDecisionDays": 5,
         "upperExclusive": 60,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "60~69",
         "lower": 60,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 124,
         "recordCount": 124,
         "uniqueDecisionDays": 5,
         "upperExclusive": 70,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "70~79",
         "lower": 70,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 36,
         "recordCount": 36,
         "uniqueDecisionDays": 5,
         "upperExclusive": 80,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "80~89",
         "lower": 80,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 2,
         "recordCount": 2,
         "uniqueDecisionDays": 1,
         "upperExclusive": 90,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "90~100",
         "lower": 90,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 101,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "기록 없음",
         "lower": null,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": null,
         "withheld": 0
        }
       ]
      },
      "total": {
       "BUY": [
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "0~39",
         "lower": 0,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 40,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "40~49",
         "lower": 40,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 50,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "50~59",
         "lower": 50,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 60,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "60~69",
         "lower": 60,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 173,
         "recordCount": 173,
         "uniqueDecisionDays": 5,
         "upperExclusive": 70,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "70~79",
         "lower": 70,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 3,
         "recordCount": 3,
         "uniqueDecisionDays": 2,
         "upperExclusive": 80,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "80~89",
         "lower": 80,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 90,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "90~100",
         "lower": 90,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 101,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "기록 없음",
         "lower": null,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": null,
         "withheld": 0
        }
       ],
       "SELL": [
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "0~39",
         "lower": 0,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 127,
         "recordCount": 127,
         "uniqueDecisionDays": 5,
         "upperExclusive": 40,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "40~49",
         "lower": 40,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 547,
         "recordCount": 547,
         "uniqueDecisionDays": 5,
         "upperExclusive": 50,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "50~59",
         "lower": 50,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 60,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "60~69",
         "lower": 60,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 70,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "70~79",
         "lower": 70,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 80,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "80~89",
         "lower": 80,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 90,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "90~100",
         "lower": 90,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": 101,
         "withheld": 0
        },
        {
         "accuracy95": null,
         "accuracyDenominator": 0,
         "accuracyPct": null,
         "blocked": 0,
         "evaluated": 0,
         "evaluatedDecisionDays": 0,
         "evidenceStatus": "INSUFFICIENT_EVIDENCE",
         "gradedDecisionDays": 0,
         "hit": 0,
         "label": "기록 없음",
         "lower": null,
         "minUniqueDecisionDays": 20,
         "miss": 0,
         "neutral": 0,
         "pending": 0,
         "recordCount": 0,
         "uniqueDecisionDays": 0,
         "upperExclusive": null,
         "withheld": 0
        }
       ]
      }
     },
     "distribution": {
      "counts": {
       "BUY": 176,
       "HOLD": 2150,
       "SELL": 674,
       "UNKNOWN": 0,
       "WITHHELD": 0
      },
      "judgedPctOfRecorded": 100.0,
      "judgedRecords": 3000,
      "observedRecords": 3000,
      "ratiosPct": {
       "BUY": 5.9,
       "HOLD": 71.7,
       "SELL": 22.5,
       "UNKNOWN": 0.0,
       "WITHHELD": 0.0
      },
      "withheldPctOfRecorded": 0.0
     },
     "failurePatterns": {
      "clusters": [],
      "droppedSmallClusters": 0,
      "maturedN": 0,
      "minSupport": {
       "days": 5,
       "rows": 8
      },
      "note": "발견은 연구 입력일 뿐이다. Production 규칙은 이 파일로 바뀌지 않는다.",
      "uniqueDays": 0,
      "wrongActionN": 0
     },
     "outcomes": {
      "accuracy95": null,
      "accuracyDenominator": 0,
      "accuracyPct": null,
      "blocked": 0,
      "evaluated": 0,
      "evaluatedDecisionDays": 0,
      "evidenceStatus": "INSUFFICIENT_EVIDENCE",
      "gradedDecisionDays": 0,
      "hit": 0,
      "minUniqueDecisionDays": 20,
      "miss": 0,
      "neutral": 0,
      "pending": 3000,
      "recordCount": 3000,
      "uniqueDecisionDays": 5,
      "withheld": 0
     }
    }
   },
   "independenceUnit": "decision_date",
   "interpretation": "INSUFFICIENT_EVIDENCE",
   "latestRound": {
    "counts": {
     "BUY": 23,
     "HOLD": 440,
     "SELL": 137,
     "UNKNOWN": 0,
     "WITHHELD": 0
    },
    "decisionAt": "2026-09-17 09:33",
    "expectedRecords": 600,
    "judgedPctOfRecorded": 100.0,
    "judgedPctOfUniverse": 100.0,
    "judgedRecords": 600,
    "missingRecords": 0,
    "observedRecords": 600,
    "ratiosPct": {
     "BUY": 3.8,
     "HOLD": 73.3,
     "SELL": 22.8,
     "UNKNOWN": 0.0,
     "WITHHELD": 0.0
    },
    "scopeStatus": "KNOWN_VERSION",
    "withheldPctOfRecorded": 0.0,
    "withheldPctOfUniverse": 0.0
   },
   "limitations": [
    "종합점수는 매수·매도 방향 점수이며 상승 확률이 아닙니다. 낮은 종합점수의 SELL을 낮은 확신으로 읽지 않습니다.",
    "확신도는 분석가 의견 일치도입니다. 같은 모델·구성·채점 기준·종목 범위끼리 나눠 봅니다.",
    "적중률은 적중과 빗나감만 나누며 중립·미래 대기·자료 부족·판단보류를 제외합니다.",
    "같은 날 여러 종목과 겹치는 5거래일 결과는 독립 시험이 아닙니다. 날짜 블록 구간도 참고 관찰입니다.",
    "판단 가능 비율과 채점 가능 비율은 다릅니다. 가격 비교 근거 부족은 과거 HOLD를 판단보류로 바꾸지 않습니다."
   ],
   "recentChange": {
    "actions": {},
    "mode": "SHADOW_ONLY",
    "observedDays": 0,
    "requiredDaysPerWindow": 20,
    "status": "INSUFFICIENT_EVIDENCE"
   },
   "schemaVersion": "actual-decision-quality-v1",
   "scoreIsProbability": false,
   "source": "actual_auto_protected_outcomes"
  },
  "rawRecordCount": 16200,
  "schemaVersion": 1,
  "source": "actual_auto",
  "status": "WAITING",
  "uniqueDecisionDays": 5
 },
 "generatedAt": "2026-09-17T00:34:36.273559+00:00",
 "gradingNote": "채점: 판단일 다음 N번째 거래일 종가 기준, 적중 정의는 기존 성적표(scoreCall)와 동일. 시장 대비 = 같은 날 분석 종목 전체 수익률 중앙값 차감.",
 "gradingPolicyVersion": "grading_v1_2026-08-16",
 "independenceNote": "같은 날 여러 종목 판단은 서로 독립이 아닙니다. 행 수와 함께 판단일 수를 같이 봐야 합니다.",
 "models": [
  {
   "autoPromotion": "NONE_MANUAL_APPROVAL_REQUIRED",
   "byCoverage": {
    "GAEO_COVERAGE_V1_500": {
     "accuracy": 51.0,
     "accuracyCI95": [
      45.4,
      57.4
     ],
     "actionDistribution": {
      "BUY": 1154,
      "HOLD": 9246,
      "SELL": 6057
     },
     "buy": {
      "count": 1154,
      "marketRelativeMeanReturn": -0.1,
      "meanReturn": -1.34,
      "medianReturn": -1.55,
      "precision": 38.2
     },
     "directionalAccuracy": 51.5,
     "directionalCI95": [
      40.5,
      63.8
     ],
     "directionalCount": 7211,
     "hold": {
      "count": 9246,
      "marketRelativeMeanReturn": -0.03,
      "meanReturn": -0.26,
      "medianReturn": -0.52,
      "precision": 50.7
     },
     "matured": 16457,
     "overallAccuracy": 51.0,
     "pending": 0,
     "sell": {
      "count": 6057,
      "marketRelativeMeanReturn": 0.47,
      "meanReturn": 0.35,
      "medianReturn": -0.95,
      "precision": 53.9
     },
     "status": "OK",
     "uniqueDates": 33
    },
    "GAEO_COVERAGE_V2_600": {
     "actionDistribution": {
      "BUY": 726,
      "HOLD": 8181,
      "SELL": 2250
     },
     "matured": 11157,
     "pending": 0,
     "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
     "status": "INSUFFICIENT_EVIDENCE",
     "uniqueDates": 19
    }
   },
   "byModelVersion": {
    "PRE_HOTFIX_BASE": {
     "accuracy": 51.0,
     "accuracyCI95": [
      45.4,
      57.4
     ],
     "actionDistribution": {
      "BUY": 1154,
      "HOLD": 9246,
      "SELL": 6057
     },
     "buy": {
      "count": 1154,
      "marketRelativeMeanReturn": -0.1,
      "meanReturn": -1.34,
      "medianReturn": -1.55,
      "precision": 38.2
     },
     "directionalAccuracy": 51.5,
     "directionalCI95": [
      40.5,
      63.8
     ],
     "directionalCount": 7211,
     "hold": {
      "count": 9246,
      "marketRelativeMeanReturn": -0.03,
      "meanReturn": -0.26,
      "medianReturn": -0.52,
      "precision": 50.7
     },
     "matured": 16457,
     "overallAccuracy": 51.0,
     "pending": 8,
     "sell": {
      "count": 6057,
      "marketRelativeMeanReturn": 0.47,
      "meanReturn": 0.35,
      "medianReturn": -0.95,
      "precision": 53.9
     },
     "status": "OK",
     "uniqueDates": 33
    },
    "base-2026-08-15-parity-hotfix": {
     "actionDistribution": {
      "BUY": 726,
      "HOLD": 8181,
      "SELL": 2250
     },
     "matured": 11157,
     "pending": 3223,
     "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
     "status": "INSUFFICIENT_EVIDENCE",
     "uniqueDates": 19
    }
   },
   "candidates": [],
   "configHash": null,
   "coverageNote": "현재 서비스는 600종목 기준입니다. 2026-08-14까지의 500종목 기록은 별도 구간으로 보존합니다.",
   "currentModelVersion": "base-2026-08-15-parity-hotfix",
   "dartUsage": "공식공시 컨텍스트·재무 신선도·안전 게이트 (방향점수 아님)",
   "displayName": "GAEO 기본모델 개선판",
   "failureReasons": null,
   "horizons": {
    "20": {
     "matured": 0,
     "pending": 0,
     "status": "NOT_APPLICABLE",
     "uniqueDates": 0
    },
    "5": {
     "actionDistribution": {
      "BUY": 726,
      "HOLD": 8181,
      "SELL": 2250
     },
     "matured": 11157,
     "note": "현재 버전(2026-08-15 hotfix 이후) 기록을 축적하는 중입니다",
     "pending": 3223,
     "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
     "status": "INSUFFICIENT_EVIDENCE",
     "uniqueDates": 19
    },
    "60": {
     "matured": 0,
     "pending": 0,
     "status": "NOT_APPLICABLE",
     "uniqueDates": 0
    }
   },
   "icon": "🟢",
   "id": "base_production",
   "internalVersion": null,
   "maturedCount": 27614,
   "note": "현재 사이트에 실제로 보이는 판단입니다.",
   "pendingCount": 3231,
   "primarySelection": null,
   "probabilityMetrics": {
    "status": "NOT_APPLICABLE"
   },
   "producesProbability": false,
   "recordCount": 30845,
   "status": "LIVE_PRODUCTION",
   "statusLabel": "실제 서비스",
   "uniquePredictionDates": 52,
   "usesDart": true,
   "withheldCount": 0
  },
  {
   "autoPromotion": "NONE_MANUAL_APPROVAL_REQUIRED",
   "candidates": [],
   "configHash": "e37e6cc0cb701171",
   "dartUsage": "사용 안 함 (완전 동결)",
   "displayName": "GAEO 연구모델 A",
   "failureReasons": null,
   "horizons": {
    "20": {
     "actionDistribution": {
      "BUY_CONSIDER": 238,
      "HOLD_WATCH": 1153,
      "SELL_CONSIDER": 236,
      "WATCH": 552
     },
     "matured": 2179,
     "pending": 12186,
     "reason": "판단일이 4일뿐입니다(최소 20일 필요)",
     "status": "INSUFFICIENT_EVIDENCE",
     "uniqueDates": 4,
     "withheld": 15
    },
    "5": {
     "actionDistribution": {
      "BUY_CONSIDER": 347,
      "HOLD_WATCH": 7514,
      "SELL_CONSIDER": 394,
      "WATCH": 2902
     },
     "matured": 11157,
     "pending": 3208,
     "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
     "status": "INSUFFICIENT_EVIDENCE",
     "uniqueDates": 19,
     "withheld": 15
    },
    "60": {
     "actionDistribution": {},
     "matured": 0,
     "pending": 14365,
     "status": "PENDING_NOT_MATURED",
     "uniqueDates": 0,
     "withheld": 15
    }
   },
   "icon": "🧪",
   "id": "research_a",
   "internalVersion": "research_v1.0",
   "note": "화면에 나오지 않는 시험용 판단입니다. 수정하지 않습니다.",
   "primarySelection": null,
   "probabilityMetrics": {
    "note": "예측 확률이 실제 빈도와 맞는지 아직 검증되지 않았습니다",
    "status": "CALIBRATION_NOT_VALIDATED"
   },
   "producesProbability": true,
   "recordCount": 14380,
   "status": "SHADOW_TESTING",
   "statusLabel": "그림자 시험",
   "uniquePredictionDates": 24,
   "usesDart": false
  },
  {
   "autoPromotion": "NONE_MANUAL_APPROVAL_REQUIRED",
   "candidates": [
    {
     "candidateModelId": "MODEL_B_EQUAL_WEIGHT__SHORT_MOMENTUM_CANDIDATE",
     "horizons": {
      "20": {
       "actionDistribution": {
        "BUY_CONSIDER": 211,
        "HOLD_WATCH": 1264,
        "SELL_CONSIDER": 203,
        "WATCH": 501
       },
       "matured": 2179,
       "pending": 12186,
       "reason": "판단일이 4일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 4,
       "withheld": 15
      },
      "5": {
       "actionDistribution": {
        "BUY_CONSIDER": 818,
        "HOLD_WATCH": 6895,
        "SELL_CONSIDER": 944,
        "WATCH": 2500
       },
       "matured": 11157,
       "pending": 3208,
       "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 19,
       "withheld": 15
      },
      "60": {
       "actionDistribution": {},
       "matured": 0,
       "pending": 14365,
       "status": "PENDING_NOT_MATURED",
       "uniqueDates": 0,
       "withheld": 15
      }
     }
    },
    {
     "candidateModelId": "MODEL_B_EQUAL_WEIGHT__SHORT_REVERSAL_CANDIDATE",
     "horizons": {
      "20": {
       "actionDistribution": {
        "BUY_CONSIDER": 211,
        "HOLD_WATCH": 1264,
        "SELL_CONSIDER": 203,
        "WATCH": 501
       },
       "matured": 2179,
       "pending": 12186,
       "reason": "판단일이 4일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 4,
       "withheld": 15
      },
      "5": {
       "actionDistribution": {
        "BUY_CONSIDER": 632,
        "HOLD_WATCH": 7432,
        "SELL_CONSIDER": 739,
        "WATCH": 2354
       },
       "matured": 11157,
       "pending": 3208,
       "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 19,
       "withheld": 15
      },
      "60": {
       "actionDistribution": {},
       "matured": 0,
       "pending": 14365,
       "status": "PENDING_NOT_MATURED",
       "uniqueDates": 0,
       "withheld": 15
      }
     }
    },
    {
     "candidateModelId": "PREDECLARED_CANDIDATE_45_35_20__SHORT_MOMENTUM_CANDIDATE",
     "horizons": {
      "20": {
       "actionDistribution": {
        "BUY_CONSIDER": 238,
        "HOLD_WATCH": 1153,
        "SELL_CONSIDER": 236,
        "WATCH": 552
       },
       "matured": 2179,
       "pending": 12186,
       "reason": "판단일이 4일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 4,
       "withheld": 15
      },
      "5": {
       "actionDistribution": {
        "BUY_CONSIDER": 736,
        "HOLD_WATCH": 6519,
        "SELL_CONSIDER": 859,
        "WATCH": 3043
       },
       "matured": 11157,
       "pending": 3208,
       "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 19,
       "withheld": 15
      },
      "60": {
       "actionDistribution": {},
       "matured": 0,
       "pending": 14365,
       "status": "PENDING_NOT_MATURED",
       "uniqueDates": 0,
       "withheld": 15
      }
     }
    },
    {
     "candidateModelId": "PREDECLARED_CANDIDATE_45_35_20__SHORT_REVERSAL_CANDIDATE",
     "horizons": {
      "20": {
       "actionDistribution": {
        "BUY_CONSIDER": 238,
        "HOLD_WATCH": 1153,
        "SELL_CONSIDER": 236,
        "WATCH": 552
       },
       "matured": 2179,
       "pending": 12186,
       "reason": "판단일이 4일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 4,
       "withheld": 15
      },
      "5": {
       "actionDistribution": {
        "BUY_CONSIDER": 347,
        "HOLD_WATCH": 7514,
        "SELL_CONSIDER": 394,
        "WATCH": 2902
       },
       "matured": 11157,
       "pending": 3208,
       "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 19,
       "withheld": 15
      },
      "60": {
       "actionDistribution": {},
       "matured": 0,
       "pending": 14365,
       "status": "PENDING_NOT_MATURED",
       "uniqueDates": 0,
       "withheld": 15
      }
     }
    }
   ],
   "configHash": "0d8ff5f0909e7b7b",
   "dartUsage": "사용 안 함 (완전 동결)",
   "displayName": "GAEO 연구모델 B",
   "failureReasons": null,
   "horizons": {
    "20": {
     "matured": 8716,
     "note": "대표 후보 없음 — 후보별 성적을 펼쳐 보세요",
     "pending": 48744,
     "status": "CANDIDATES_UNDER_TEST",
     "uniqueDates": 24
    },
    "5": {
     "matured": 44628,
     "note": "대표 후보 없음 — 후보별 성적을 펼쳐 보세요",
     "pending": 12832,
     "status": "CANDIDATES_UNDER_TEST",
     "uniqueDates": 24
    },
    "60": {
     "matured": 0,
     "note": "대표 후보 없음 — 후보별 성적을 펼쳐 보세요",
     "pending": 57460,
     "status": "CANDIDATES_UNDER_TEST",
     "uniqueDates": 24
    }
   },
   "icon": "🧪",
   "id": "research_b",
   "internalVersion": "research_v1.1",
   "note": "후보 4개를 동시에 시험 중이며 대표 후보를 고르지 않았습니다.",
   "primarySelection": "NO_PRIMARY_CANDIDATE_SELECTED",
   "probabilityMetrics": {
    "note": "예측 확률이 실제 빈도와 맞는지 아직 검증되지 않았습니다",
    "status": "CALIBRATION_NOT_VALIDATED"
   },
   "producesProbability": true,
   "recordCount": 14380,
   "status": "SHADOW_TESTING",
   "statusLabel": "그림자 시험",
   "uniquePredictionDates": 24,
   "usesDart": false
  },
  {
   "autoPromotion": "NONE_MANUAL_APPROVAL_REQUIRED",
   "candidates": [
    {
     "candidateModelId": "MODEL_B_EQUAL_WEIGHT__SHORT_MOMENTUM_CANDIDATE",
     "horizons": {
      "20": {
       "actionDistribution": {
        "BUY_CONSIDER": 211,
        "HOLD_WATCH": 1264,
        "SELL_CONSIDER": 203,
        "WATCH": 501
       },
       "matured": 2179,
       "pending": 12186,
       "reason": "판단일이 4일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 4,
       "withheld": 15
      },
      "5": {
       "actionDistribution": {
        "BUY_CONSIDER": 818,
        "HOLD_WATCH": 6895,
        "SELL_CONSIDER": 944,
        "WATCH": 2500
       },
       "matured": 11157,
       "pending": 3208,
       "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 19,
       "withheld": 15
      },
      "60": {
       "actionDistribution": {},
       "matured": 0,
       "pending": 14365,
       "status": "PENDING_NOT_MATURED",
       "uniqueDates": 0,
       "withheld": 15
      }
     }
    },
    {
     "candidateModelId": "MODEL_B_EQUAL_WEIGHT__SHORT_REVERSAL_CANDIDATE",
     "horizons": {
      "20": {
       "actionDistribution": {
        "BUY_CONSIDER": 211,
        "HOLD_WATCH": 1264,
        "SELL_CONSIDER": 203,
        "WATCH": 501
       },
       "matured": 2179,
       "pending": 12186,
       "reason": "판단일이 4일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 4,
       "withheld": 15
      },
      "5": {
       "actionDistribution": {
        "BUY_CONSIDER": 632,
        "HOLD_WATCH": 7432,
        "SELL_CONSIDER": 739,
        "WATCH": 2354
       },
       "matured": 11157,
       "pending": 3208,
       "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 19,
       "withheld": 15
      },
      "60": {
       "actionDistribution": {},
       "matured": 0,
       "pending": 14365,
       "status": "PENDING_NOT_MATURED",
       "uniqueDates": 0,
       "withheld": 15
      }
     }
    },
    {
     "candidateModelId": "PREDECLARED_CANDIDATE_45_35_20__SHORT_MOMENTUM_CANDIDATE",
     "horizons": {
      "20": {
       "actionDistribution": {
        "BUY_CONSIDER": 238,
        "HOLD_WATCH": 1153,
        "SELL_CONSIDER": 236,
        "WATCH": 552
       },
       "matured": 2179,
       "pending": 12186,
       "reason": "판단일이 4일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 4,
       "withheld": 15
      },
      "5": {
       "actionDistribution": {
        "BUY_CONSIDER": 736,
        "HOLD_WATCH": 6519,
        "SELL_CONSIDER": 859,
        "WATCH": 3043
       },
       "matured": 11157,
       "pending": 3208,
       "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 19,
       "withheld": 15
      },
      "60": {
       "actionDistribution": {},
       "matured": 0,
       "pending": 14365,
       "status": "PENDING_NOT_MATURED",
       "uniqueDates": 0,
       "withheld": 15
      }
     }
    },
    {
     "candidateModelId": "PREDECLARED_CANDIDATE_45_35_20__SHORT_REVERSAL_CANDIDATE",
     "horizons": {
      "20": {
       "actionDistribution": {
        "BUY_CONSIDER": 238,
        "HOLD_WATCH": 1153,
        "SELL_CONSIDER": 236,
        "WATCH": 552
       },
       "matured": 2179,
       "pending": 12186,
       "reason": "판단일이 4일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 4,
       "withheld": 15
      },
      "5": {
       "actionDistribution": {
        "BUY_CONSIDER": 347,
        "HOLD_WATCH": 7514,
        "SELL_CONSIDER": 394,
        "WATCH": 2902
       },
       "matured": 11157,
       "pending": 3208,
       "reason": "판단일이 19일뿐입니다(최소 20일 필요)",
       "status": "INSUFFICIENT_EVIDENCE",
       "uniqueDates": 19,
       "withheld": 15
      },
      "60": {
       "actionDistribution": {},
       "matured": 0,
       "pending": 14365,
       "status": "PENDING_NOT_MATURED",
       "uniqueDates": 0,
       "withheld": 15
      }
     }
    }
   ],
   "configHash": null,
   "dartUsage": "공시 존재·탐지시각·정정·커버리지 (Point-in-Time)",
   "displayName": "GAEO 연구모델 C",
   "failureReasons": null,
   "horizons": {
    "20": {
     "matured": 8716,
     "note": "대표 후보 없음 — 후보별 성적을 펼쳐 보세요",
     "pending": 48744,
     "status": "CANDIDATES_UNDER_TEST",
     "uniqueDates": 24
    },
    "5": {
     "matured": 44628,
     "note": "대표 후보 없음 — 후보별 성적을 펼쳐 보세요",
     "pending": 12832,
     "status": "CANDIDATES_UNDER_TEST",
     "uniqueDates": 24
    },
    "60": {
     "matured": 0,
     "note": "대표 후보 없음 — 후보별 성적을 펼쳐 보세요",
     "pending": 57460,
     "status": "CANDIDATES_UNDER_TEST",
     "uniqueDates": 24
    }
   },
   "icon": "🧪",
   "id": "research_c",
   "internalVersion": "research_v2.0",
   "note": "연구모델 B와 같은 조건에 공시 정보만 더한 짝을 만들어 비교합니다.",
   "primarySelection": "NO_PRIMARY_CANDIDATE_SELECTED",
   "probabilityMetrics": {
    "note": "예측 확률이 실제 빈도와 맞는지 아직 검증되지 않았습니다",
    "status": "CALIBRATION_NOT_VALIDATED"
   },
   "producesProbability": true,
   "recordCount": 14380,
   "status": "SHADOW_STARTING",
   "statusLabel": "준비중",
   "uniquePredictionDates": 24,
   "usesDart": true
  },
  {
   "autoPromotion": "REMOVED",
   "candidates": [],
   "configHash": null,
   "dartUsage": "사용 안 함",
   "displayName": "구형 그림자모델",
   "failureReasons": [
    "SELL 판단이 전체의 41%로 극단적으로 치우쳤습니다.",
    "상승장에서 SELL 적중률이 9.4%까지 무너졌습니다(하락장 85.9%).",
    "승격 기준을 통과하지 못한 채 자동승격 경로만 남아 있었습니다."
   ],
   "horizons": {
    "20": {
     "matured": 0,
     "pending": 0,
     "status": "NOT_APPLICABLE",
     "uniqueDates": 0
    },
    "5": {
     "matured": 0,
     "pending": 0,
     "status": "ARCHIVED_NO_NEW_PREDICTIONS",
     "uniqueDates": 0
    },
    "60": {
     "matured": 0,
     "pending": 0,
     "status": "NOT_APPLICABLE",
     "uniqueDates": 0
    }
   },
   "icon": "🗄️",
   "id": "legacy_shadow_v3",
   "internalVersion": "calibrated-ensemble-v3",
   "note": "신규 예측을 중단했습니다. 과거 기록은 그대로 보존합니다.",
   "primarySelection": null,
   "probabilityMetrics": {
    "note": "예측 확률이 실제 빈도와 맞는지 아직 검증되지 않았습니다",
    "status": "CALIBRATION_NOT_VALIDATED"
   },
   "producesProbability": true,
   "recordCount": 0,
   "status": "ARCHIVED_FAILED_EXPERIMENT",
   "statusLabel": "보관 (실패 사례)",
   "uniquePredictionDates": 0,
   "usesDart": false
  }
 ],
 "pairedComparisons": [
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "base_production",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_a"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "base_production",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_b:MODEL_B_EQUAL_WEIGHT__SHORT_MOMENTUM_CANDIDATE"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "base_production",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_b:MODEL_B_EQUAL_WEIGHT__SHORT_REVERSAL_CANDIDATE"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "base_production",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_b:PREDECLARED_CANDIDATE_45_35_20__SHORT_MOMENTUM_CANDIDATE"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "base_production",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_b:PREDECLARED_CANDIDATE_45_35_20__SHORT_REVERSAL_CANDIDATE"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "base_production",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_c:MODEL_B_EQUAL_WEIGHT__SHORT_MOMENTUM_CANDIDATE"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "base_production",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_c:MODEL_B_EQUAL_WEIGHT__SHORT_REVERSAL_CANDIDATE"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "base_production",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_c:PREDECLARED_CANDIDATE_45_35_20__SHORT_MOMENTUM_CANDIDATE"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "base_production",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_c:PREDECLARED_CANDIDATE_45_35_20__SHORT_REVERSAL_CANDIDATE"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "research_b:MODEL_B_EQUAL_WEIGHT__SHORT_MOMENTUM_CANDIDATE",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_c:MODEL_B_EQUAL_WEIGHT__SHORT_MOMENTUM_CANDIDATE"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "research_b:MODEL_B_EQUAL_WEIGHT__SHORT_REVERSAL_CANDIDATE",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_c:MODEL_B_EQUAL_WEIGHT__SHORT_REVERSAL_CANDIDATE"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "research_b:PREDECLARED_CANDIDATE_45_35_20__SHORT_MOMENTUM_CANDIDATE",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_c:PREDECLARED_CANDIDATE_45_35_20__SHORT_MOMENTUM_CANDIDATE"
  },
  {
   "evidenceStatus": "INSUFFICIENT_EVIDENCE",
   "horizon": "5D",
   "leftModel": "research_b:PREDECLARED_CANDIDATE_45_35_20__SHORT_REVERSAL_CANDIDATE",
   "matchedRows": 11157,
   "matchedUniqueDates": 19,
   "note": "차이를 판단하기 이릅니다",
   "rightModel": "research_c:PREDECLARED_CANDIDATE_45_35_20__SHORT_REVERSAL_CANDIDATE"
  }
 ],
 "policyNote": "어떤 모델도 스스로 실제 서비스 판단을 바꾸지 않습니다. 기준을 충족하면 '승격 검토 가능' 표시만 나오고, 실제 적용은 사람이 따로 승인해야 합니다.",
 "ranking": {
  "reason": "같은 Horizon·같은 표본·충분한 판단일이 갖춰지기 전에는 순위를 매기지 않습니다.",
  "status": "RANKING_ON_HOLD"
 },
 "regimeSplit": {
  "note": "판단 당시 알 수 있었던 정보로만 장세를 나누려면 성숙한 기록이 더 필요합니다.",
  "status": "REGIME_DATA_INSUFFICIENT"
 },
 "researchKeyAvailable": true,
 "researchRecordDays": 24,
 "schemaVersion": "gaeo_model_registry_v1"
};
