// Real rendering boundary: missing counts must stay unknown; labels cannot become orders.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const app=fs.readFileSync(__dirname+'/app.js','utf8');
const ui=fs.readFileSync(__dirname+'/scorecard-ui.js','utf8');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ctx={esc,window:{},liveInd:()=>({tech:{rsi14:41,ma20:1200},risk:{vol20:2.3},flow:{frgnSum:100,orgSum:-20,periodEnd:'2026-09-10'}}),analysisAsOf:()=>null};
vm.createContext(ctx);
const shared=app.slice(app.indexOf('function gaeoJudgmentDisplay('),app.indexOf('/* 홈 「오늘의 판단」 각주'));
assert.ok(shared.length,'Shared display helper is missing');
vm.runInContext(shared,ctx);
const traceCode=ui.slice(ui.indexOf('function decisionTraceHTML('),ui.indexOf('function renderScorecard('));
vm.runInContext(traceCode,ctx);
for(const [call,label] of [['BUY','매수 검토'],['HOLD','지켜보기'],['SELL','매도 검토'],['JUDGMENT_WITHHELD','판단 보류'],['???','판단 보류'],['constructor','판단 보류'],['__proto__','판단 보류']]){
  assert.equal(ctx.gaeoJudgmentDisplay(call).label,label);
  assert.ok(ctx.gaeoJudgmentDisplay(call).explanation.length>12);
}
const horizon={evaluated:7,pending:2,blocked:3,withheld:1,hit:4,miss:2,neutral:1,accuracy:null,accuracyDenominator:6,evaluatedDecisionDays:3,evidenceStatus:'RECORDS_ACCUMULATING',reasons:{future_session:2,missing_price:2,unknown_future_reason:1}};
const trace={schemaVersion:1,status:'PARTIAL',rawRecordCount:16,dailyRecordCount:13,uniqueDecisionDays:3,latestDecisionAt:'2026-09-11T15:40:00+09:00',lastVerifiedAt:'2026-09-13T12:00:00+09:00',currentModelVersion:'v-now',source:'actual_auto',horizons:{'5':horizon},byModelVersion:{'v-now':{rawRecordCount:10,dailyRecordCount:8,uniqueDecisionDays:2,horizons:{'5':horizon}},'v-past':{rawRecordCount:6,dailyRecordCount:5,uniqueDecisionDays:1,horizons:{'5':horizon}}},disclosure:{statuses:{event_found:2,checked_no_event:3,unavailable:4,needs_review:1}},examples:[{recordId:'<unsafe>',code:'080220',decisionAt:'2026-09-11',call:'HOLD',base:1200,status:'blocked',reason:'corporate_action_unverified',sourcePath:'javascript:alert(1)'}],limitations:['테스트 범위 한계']};
let rendered=ctx.decisionTraceHTML(trace);
for(const text of ['16','13','3','현재 모델','과거 모델','자료 확인 필요','가격 자료 미확인','거래일 경과 대기','4 ÷ (4 + 2)','중립','판단 보류','테스트 범위 한계','&lt;unsafe&gt;','지켜보기']) assert.ok(rendered.includes(text),text);
assert.doesNotMatch(rendered,/66\.7%|javascript:|<unsafe>/);
assert.match(rendered,/결과 기다리는 중/);
assert.match(rendered,/자료 부족으로 평가 보류/);
assert.match(rendered,/기록을 더 모으는 중/);
const linked=ctx.decisionTraceHTML({...trace,examples:[{...trace.examples[0],sourcePath:'research_archive/decisions/originals/2026/09/11/1234567890abcdef12345678.jsonl.gz',outcomePath:'research_archive/decisions/outcomes/2026-09.json'}]});
assert.match(linked,/href="https:\/\/github.com\/rudvh1016-gif\/gaeo-analyst-team\/blob\/main\/research_archive\/decisions\/originals\/2026\/09\/11\/1234567890abcdef12345678.jsonl.gz"/);
assert.match(linked,/href="https:\/\/github.com\/rudvh1016-gif\/gaeo-analyst-team\/blob\/main\/research_archive\/decisions\/outcomes\/2026-09.json"/);
const traversal=ctx.decisionTraceHTML({...trace,examples:[{...trace.examples[0],sourcePath:'research_archive/decisions/originals/../private.json'}]});
assert.doesNotMatch(traversal,/href=/);
assert.match(rendered,/같은 날.*독립/);
const unknown=ctx.decisionTraceHTML({schemaVersion:1,horizons:{'5':{}}});
assert.match(unknown,/자료 확인 중/);
assert.doesNotMatch(unknown,/>0<|적중률 0%|사건 발견 0건|원본 0건/);
assert.match(ctx.decisionTraceHTML(null),/자료 확인 중/);
rendered=ctx.decisionTraceHTML({...trace,horizons:{'5':{...horizon,accuracy:66.7}}});
assert.match(rendered,/66\.7%/);
const evidence=ctx.gaeoBeginnerEvidenceHTML({code:'080220',per:0,pbr:1.2});
for(const text of ['RSI','PER','PBR','변동성','수급','이동평균','2026-09-10','장중 실시간','자료 확인 중']) assert.ok(evidence.includes(text),text);
assert.doesNotMatch(evidence,/undefined|NaN/);
ctx.MODEL_SCOREBOARD={decisionTrace:{disclosure:{byCode:{'080220':'checked_no_event'},observedAt:'2026-09-13T04:00:00Z',scope:'최근 공시·페이지 확인 범위'}}};
const disclosure=ctx.gaeoDisclosureEvidenceHTML('080220');
assert.match(disclosure,/확인 범위 내 사건 없음/);
assert.match(disclosure,/2026-09-13T04:00:00Z/);
assert.match(disclosure,/분석 당시/);
assert.match(ctx.gaeoDisclosureEvidenceHTML('MISSING'),/확인 불가/);
vm.runInContext(app.slice(app.indexOf('function baseReliabilityState('),app.indexOf('// 2. 판단 이유 3가지')),ctx);
ctx.MODEL_SCOREBOARD={models:[{id:'base_production',currentModelVersion:'old',byModelVersion:{old:{accuracy:88}}}]};
assert.equal(ctx.baseReliabilityState().kind,'UNKNOWN','Legacy accuracy cannot certify current decision trace');
ctx.MODEL_SCOREBOARD={decisionTrace:{currentModelVersion:'v-now',byModelVersion:{'v-now':{horizons:{'5':{accuracy:null}}}}}};
assert.equal(ctx.baseReliabilityState().kind,'ACCUMULATING');
ctx.MODEL_SCOREBOARD.decisionTrace.byModelVersion['v-now'].horizons['5'].accuracy=61.2;
assert.equal(ctx.baseReliabilityState().acc,61.2);
console.log('beginner judgment render tests passed');
